package org.pklose.espl.generator.flow;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.pklose.espl.generator.HTMLGenerator;

@SuppressWarnings("all")
public class FlowBody implements HTMLGenerator {
  private final String flowName;
  
  public FlowBody(final String flowName) {
    this.flowName = flowName;
  }
  
  public Object getHTML() {
    return null;
  }
  
  @Override
  public String getAsHTML() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html>");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("<title>State Chart</title>");
    _builder.newLine();
    _builder.append("<meta name=\"description\" content=\"A finite state machine chart with editable and interactive features.\" />");
    _builder.newLine();
    _builder.append("<!-- /* Copyright 1998-2016 by Northwoods Software Corporation. */ -->");
    _builder.newLine();
    _builder.append("<meta charset=\"UTF-8\">");
    _builder.newLine();
    _builder.append("<script src=\"http://gojs.net/latest/release/go.js\"></script>");
    _builder.newLine();
    _builder.append("<script id=\"code\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("function init() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("var $ = go.GraphObject.make;  // for conciseness in defining templates");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("myDiagram =");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("$(go.Diagram, \"myDiagram\",  // must name or refer to the DIV HTML element");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("// start everything in the middle of the viewport");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("initialContentAlignment: go.Spot.Left,");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("layout: $(go.LayeredDigraphLayout)");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// define the Node template");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("myDiagram.nodeTemplate =");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("$(go.Node, \"Auto\",");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("new go.Binding(\"location\", \"loc\", go.Point.parse).makeTwoWay(go.Point.stringify),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("// define the node\'s outer shape, which will surround the TextBlock");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(go.Shape, \"RoundedRectangle\",");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("parameter1: 20,  // the corner has a large radius");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("fill: $(go.Brush, \"Linear\", { 0: \"rgb(254, 201, 0)\", 1: \"rgb(254, 162, 0)\" }),");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("stroke: \"black\",");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("portId: \"\",");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("fromLinkable: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("fromLinkableSelfNode: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("fromLinkableDuplicates: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("toLinkable: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("toLinkableSelfNode: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("toLinkableDuplicates: true,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("cursor: \"pointer\"");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("}),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(go.TextBlock,");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("font: \"bold 11pt helvetica, bold arial, sans-serif\",");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("editable: false");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("},");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("new go.Binding(\"text\", \"text\").makeTwoWay())");
    _builder.newLine();
    _builder.append("      ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// replace the default Link template in the linkTemplateMap");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("myDiagram.linkTemplate =");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("$(go.Link,  // the whole link panel");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("{ curve: go.Link.Bezier, adjusting: go.Link.Stretch, reshapable: true },");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("new go.Binding(\"curviness\", \"curviness\"),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("new go.Binding(\"points\").makeTwoWay(),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(go.Shape,  // the link shape");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("{ strokeWidth: 1.5 }),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(go.Shape,  // the arrowhead");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("{ toArrow: \"standard\", stroke: null }),");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(go.Panel, \"Auto\",");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("$(go.Shape,  // the link shape");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("fill: $(go.Brush, \"Radial\",");
    _builder.newLine();
    _builder.append("                      ");
    _builder.append("{ 0: \"rgb(240, 240, 240)\", 0.3: \"rgb(240, 240, 240)\", 1: \"rgba(240, 240, 240, 0)\" }),");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("stroke: null");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}),");
    _builder.newLine();
    _builder.append("          ");
    _builder.append("$(go.TextBlock, \"transition\",  // the label");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("textAlign: \"center\",");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("font: \"10pt helvetica, arial, sans-serif\",");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("stroke: \"black\",");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("margin: 4,");
    _builder.newLine();
    _builder.append("              ");
    _builder.append("editable: false  // editing the text automatically updates the model data");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("},");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("new go.Binding(\"text\", \"text\").makeTwoWay())");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(")");
    _builder.newLine();
    _builder.append("      ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("// read in the JSON-format data from the \"mySavedModel\" element");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("load();");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("function load() {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("myDiagram.model = go.Model.fromJson(");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("{ \"nodeKeyProperty\": \"id\",");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"nodeDataArray\": [");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"id\": 0, \"loc\": \"120 120\", \"text\": \"Initial\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"id\": 1, \"loc\": \"330 120\", \"text\": \"First down\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"id\": 2, \"loc\": \"226 376\", \"text\": \"First up\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"id\": 3, \"loc\": \"60 276\", \"text\": \"Second down\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"id\": 4, \"loc\": \"226 226\", \"text\": \"Wait\" }");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("],");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("\"linkDataArray\": [");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 0, \"to\": 0, \"text\": \"up or timer\", \"curviness\": -20 },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 0, \"to\": 1, \"text\": \"down\", \"curviness\": 20 },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 1, \"to\": 0, \"text\": \"up (moved)\\nPOST\", \"curviness\": 20 },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 1, \"to\": 1, \"text\": \"down\", \"curviness\": -20 },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 1, \"to\": 2, \"text\": \"up (no move)\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 1, \"to\": 4, \"text\": \"timer\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 2, \"to\": 0, \"text\": \"timer\\nPOST\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 2, \"to\": 3, \"text\": \"down\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 3, \"to\": 0, \"text\": \"up\\nPOST\\n(dblclick\\nif no move)\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 3, \"to\": 3, \"text\": \"down or timer\", \"curviness\": 20 },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 4, \"to\": 0, \"text\": \"up\\nPOST\" },");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("{ \"from\": 4, \"to\": 4, \"text\": \"down\" }]");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    _builder.append("</head>");
    _builder.newLine();
    _builder.append("<body onload=\"init()\">");
    _builder.newLine();
    _builder.append("<div id=\"sample\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<div id=\"myDiagram\" style=\"background-color: whitesmoke; border: solid 1px black; width: 100%; height: 400px\"></div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder.toString();
  }
}
