/*
 * generated by Xtext
 */
package org.pklose.espl.validation

import org.eclipse.xtext.validation.Check
import org.pklose.espl.esplm.BusinessRule
import org.pklose.espl.esplm.BREType
import org.pklose.espl.esplm.BreEntityInput
import org.pklose.espl.esplm.EsplmPackage
import org.pklose.espl.esplm.BreSystemEntityInput

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class EsplmValidator extends AbstractEsplmValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkBREInputTypesMatch (BusinessRule businessRule) {
		if (BREType.BIZ_TO_BIZ.equals(businessRule.typ)) {			
			if (!businessRule.systemInputs.forall[it instanceof BreEntityInput]) {
				error('Für BizToBiz sind nur Entitäten als Input erlaubt', EsplmPackage.Literals.BRE_SYSTEM_ENTITY_INPUT__INPUT_ELEMENT);
			}
		}
		
		if (BREType.SRC_TO_BIZ.equals(businessRule.typ)) {
			if (BREType.SRC_TO_BIZ.equals(businessRule.typ)) {
				if (!businessRule.systemInputs.forall[it instanceof BreSystemEntityInput]) {
					error ('Für SrcToBiz sind nur Src Entitäten als Input erlaubt', EsplmPackage.Literals.BRE_SYSTEM_ENTITY_INPUT__INPUT_ELEMENT)
				}
			}		
		}
	}
}
