/*
 * generated by Xtext
 */
package org.pklose.espl.validation

import org.eclipse.xtext.validation.Check
import org.pklose.espl.esplm.BusinessRule
import org.pklose.espl.esplm.BREType
import org.pklose.espl.esplm.BreEntityInput

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class EsplmValidator extends AbstractEsplmValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkBREInputTypesMatch (BusinessRule businessRule) {
		if (BREType.BIZ_TO_BIZ.equals(businessRule.typ)) {			
			if (!businessRule.systemInputs.forall[it instanceof BreEntityInput]) {
				
			}
		}
	}
}
