/*
 * generated by Xtext
 */
package org.pklose.espl.validation

import org.eclipse.xtext.validation.Check
import org.pklose.espl.esplm.BREType
import org.pklose.espl.esplm.BreEntityInput
import org.pklose.espl.esplm.BusinessRule
import org.pklose.espl.esplm.EsplmPackage
import org.pklose.espl.esplm.Entity
import org.pklose.espl.esplm.SystemEntity
import org.eclipse.emf.common.util.EList
import java.util.List

//import org.eclipse.xtext.validation.Check
/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class EsplmValidator extends AbstractEsplmValidator {

	final val SRC_TO_BIZ_ERROR = 'Für SrcToBiz sind nur Src Entitäten als Input erlaubt'
	final val BIZ_TO_BIZ_ERROR = 'Für BizToBiz sind nur Entitäten als Input erlaubt'

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkBREInputTypesMatch(BusinessRule businessRule) {
		var List<BreEntityInput> inputElements = businessRule.inputs as List<BreEntityInput>
		for (BreEntityInput bre : (businessRule.inputs as EList<BreEntityInput>)) {
			if (BREType.BIZ_TO_BIZ.equals(businessRule.typ)) {
				if (bre.inputElement instanceof SystemEntity) {
					error(BIZ_TO_BIZ_ERROR, bre, EsplmPackage.Literals.BRE_ENTITY_INPUT__INPUT_ELEMENT);
				}
			}

			if (BREType.SRC_TO_BIZ.equals(businessRule.typ)) {
				if (bre.inputElement instanceof Entity) {
					error(SRC_TO_BIZ_ERROR, bre, EsplmPackage.Literals.BRE_ENTITY_INPUT__INPUT_ELEMENT);
				}				
			}

		}
	}
}

