/*
 * generated by Xtext
 */
package org.pklose.espl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.pklose.espl.ui.internal.EsplmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EsplmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EsplmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EsplmActivator.getInstance().getInjector(EsplmActivator.ORG_PKLOSE_ESPL_ESPLM);
	}
	
}
