/*
 * generated by Xtext
 */
package org.pklose.espl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EsplmUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.pklose.espl.ui.internal.EsplmActivator.getInstance().getInjector("org.pklose.espl.Esplm");
	}
	
}
