/*
 * generated by Xtext
 */
package org.pklose.espl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.pklose.espl.services.EsplmGrammarAccess;

public class EsplmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EsplmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.pklose.espl.parser.antlr.internal.InternalEsplmParser createParser(XtextTokenStream stream) {
		return new org.pklose.espl.parser.antlr.internal.InternalEsplmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EsplmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EsplmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
