/**
 * generated by Xtext
 */
package org.pklose.espl.validation;

import org.pklose.espl.validation.AbstractEsplmValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EsplmValidator extends AbstractEsplmValidator {
}
