/**
 * generated by Xtext
 */
package org.pklose.espl.ui.contentassist;

import org.pklose.espl.ui.contentassist.AbstractEsplmProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EsplmProposalProvider extends AbstractEsplmProposalProvider {
}
