/*
 * generated by Xtext
 */
package org.pklose.espl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EsplmUiModule extends org.pklose.espl.ui.AbstractEsplmUiModule {
	public EsplmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
