/*
 * generated by Xtext
 */
package org.pklose.espl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EsplmRuntimeModule extends org.pklose.espl.AbstractEsplmRuntimeModule {

}
