/*
 * generated by Xtext
 */
package org.pklose.espl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EsplmStandaloneSetup extends EsplmStandaloneSetupGenerated{

	public static void doSetup() {
		new EsplmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

