/*
 * generated by Xtext
 */
package org.pklose.espl;

import org.pklose.espl.abinitio.service.AbinitionServicesModule;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EsplmStandaloneSetup extends EsplmStandaloneSetupGenerated{

	public static void doSetup() {
		Injector createInjectorAndDoEMFRegistration = new EsplmStandaloneSetup().createInjectorAndDoEMFRegistration();
		createInjectorAndDoEMFRegistration.createChildInjector(new AbinitionServicesModule());
	}
}

